---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
      name: '{{ hostname }}'

- name: Add mapping to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
      path: /etc/hosts
      line: '127.0.0.1 {{ hostname }}'
      state: present
  notify: Restart networkd
